### ISSUE TITLE
If directory is empty an exception is thrown

### ISSUE THREAD

**Issue by dplocki** [dplocki/podcast-downloader#13]
**Describe the bug**
If you trying to check the empty directory, an exception is thrown.

**To Reproduce**
1. setup podcast
2. make sure, that the directory of it is empty
3. run script

**Additional context**
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 79, in <module>
    last_downloaded_file = get_last_downloaded(rss_source_path)
  File "downloaded.py", line 23, in get_last_downloaded
    return next(get_downloaded_files(podcast_directory))
StopIteration
```

**Comment by dplocki** [comment]
Already done.
